### ISSUE TITLE
1MB logo ?

### ISSUE THREAD

**Issue by kuldeepdhaka** [LinuxChixIndia/LinuxChixIndia.github.io#10]
The Logo (https://linuxchixindia.github.io/assets/img/logo_transparent.png)
is ~1MB.
This severly effect the loading time.

Why not switch to SVG?

**Comment by kuldeepdhaka** [comment]
Since you are assuming browser support gradient (ie modern browser), it will possibly support SVG too.

**Comment by CuriousLearner** [comment]
We need people to come forward and help :) 
Please feel free to issue a PR.

I agree, that the logo size is really large which is time-consuming on a HTTP connection.

**Comment by CuriousLearner** [comment]
Fixed in PR #11
