### ISSUE TITLE
rel="noopener noreferrer" missing along with target="_blank".

### ISSUE THREAD

**Issue by SaptakS** [LinuxChixIndia/LinuxChixIndia.github.io#17]
`target="_blank"` without `rel="noopener noreferrer"` may cause reverse tabnabbing. You can check this blog: https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/

**Comment by CuriousLearner** [comment]
Fixed in 2dbd95b
